package com.campus.certificate.domain;

public enum CertificateCategory {
    ACADEMIC_EDUCATION,
    LANGUAGE_EXAM,
    PROFESSIONAL_QUALIFICATION,
    SKILL_CERTIFICATION,
    COMPETITION_AWARD,
    INNOVATION_ENTREPRENEURSHIP,
    TRAINING_CERTIFICATE,
    HONORARY_TITLE,
    CULTURE_SPORTS,
    SOCIAL_PRACTICE,
    VOLUNTEER_SERVICE,
    INTELLECTUAL_PROPERTY,
    OTHER
}

