UPDATE certificates
SET category = CASE category
    WHEN 'COMPETITION' THEN 'ACADEMIC_COMPETITION'
    WHEN 'HONOR' THEN 'HONORARY_TITLE'
    ELSE 'OTHER'
END
WHERE category IN ('LANGUAGE', 'PROFESSIONAL', 'COMPETITION', 'SKILL', 'ACADEMIC', 'HONOR', 'OTHER');
